### ISSUE TITLE
Does not work in ESM

### ISSUE THREAD

**Issue by kran6a** [mmkal/trpc-cli#7]
Reproduction
```typescript
import {initTRPC} from '@trpc/server';
import {z} from 'zod';
import {trpcCli} from 'trpc-cli';

const t = initTRPC.create();

export const router = t.router({
    add: t.procedure
        .input(z.object({left: z.number(), right: z.number()}))
        .query(({input}) => input.left + input.right),
});

const cli = trpcCli({router});
await cli.run();
```

If you add console.log({parsedArgv}) on trpc-cli index.ts you can see why it does not work:
```json
[
  [
    "add",
    "Invalid input type ZodObject, only zod inputs are supported"
  ]
]
```

Apparently import {z} from "zod" and require("zod") are not importing the same classes thus instanceof does not work as intended.

**Comment by mmkal** [comment]
Interesting, sounds like zod has the dual-package hazard. Probably can be worked around by making a helper function with a guard return type, which checks the constructor name or something.

**Comment by mmkal** [comment]
@kran6a I just published a prerelease version which should help with this. You can install with `npm install trpc-cli@0.3.1-0`.

I was able to repro the issue and that the new version fixes. https://github.com/mmkal/trpc-cli/pull/8. Could you try it out?

**Comment by kran6a** [comment]
It works! Thanks for the quick fix
